### ISSUE TITLE
pylibmc is not thread-safe

### ISSUE THREAD

**Issue by cedk** [sh4nks/flask-caching#113] opened 2019-05-10 07:19 UTC
The way pylibmc client is used is not thread-safe.
I think flask-caching should use the [ThreadMappedPool](http://sendapatch.se/projects/pylibmc/pooling.html#thread-mapped-pooling).
Otherwise on threaded Flask application, we must use python-memcached but there is no way to force to use this library.

**Comment by reubano** [comment] 2019-08-18 06:08
I think I've run into this issue. While running on heroku, not all instances of the cache respect `CACHE_DEFAULT_TIMEOUT`. It took me ages to figure out why my cache was clearing after 5 minutes, despite having set `CACHE_DEFAULT_TIMEOUT` for longer.

**Comment by reubano** [comment] 2019-08-20 23:06
I'm using `python-binary-memcached>=0.26.1,<0.27.0`

**Comment by sh4nks** [comment] 2019-11-24 17:23
Actually this is not a bug. If you need a threadsafe memcache backend, you can just subclass the existing one and add it there. The reason I am not adding it is as due to the fact that the ThreadMappedPool is only supported by pylibmc and we are supporting 4 different memcache libraries.

**Comment by cedk** [comment] 2019-11-24 17:37
Then maybe pylibmc should not be the first library to use as its client is not thread safe by default.

**Comment by sh4nks** [comment] 2019-11-24 17:54
Yeah maybe. I am happy to review a PR if you want to submit one :-)

**Comment by reubano** [comment] 2019-11-24 17:56
@cedk can you outline the steps you took to get thread safe behavior with `python-memcached`?

**Comment by sh4nks** [comment] 2020-05-31 11:09
I am closing this issue for now. As I have said before, I'd happily review a PR if someone wants to implement this.

**Closed by sh4nks** 2020-05-31 11:09 UTC
Labels: question
